name: 功能建议
description: 提出一个明确的改进/新功能（请讲清楚问题与收益）
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        只收「具体且可落地」的建议。空泛愿望=无法评估。

  - type: checkboxes
    id: preflight
    attributes:
      label: 提交前检查（必选）
      options:
        - label: 我已搜索现有 Issues，确认不是重复需求
          required: true
        - label: 这是 Vea 本身应做的事（不是上游 Xray/sing-box 的功能请求）
          required: true

  - type: dropdown
    id: scope
    attributes:
      label: 影响范围
      options:
        - FRouter / 链式代理图
        - ProxyConfig / 入站模式（SOCKS/HTTP/Mixed/TUN）
        - 节点 / 订阅 / 导入
        - 测速 / 延迟 / 探测
        - 组件 / Geo / 核心下载与校验
        - 前端 UI / 交互
        - HTTP API / SDK
        - 文档
        - 其他
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: 你想解决什么问题（Use case）
      description: 先讲问题与目标，不要一上来就讲实现细节。
      placeholder: |
        - 当前遇到的痛点是什么？
        - 你希望达到的结果是什么？
        - 谁会受益、为什么？
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 你希望怎么做（建议方案）
      description: 可以包含 UI 草图、交互流程、API 形状、配置示例等；越具体越好。
      placeholder: |
        例如：
        - UI：在 FRouter 编辑页增加 ...
        - 后端：新增一个 /settings/... 的字段用于 ...
        - 规则：local->* 的选择边支持 ...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 / 现有绕过方式
      description: 你现在怎么解决？为什么不够？
      placeholder: |
        - 目前的 workaround 是 ...
        - 不足之处是 ...
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: 补充信息
      description: 截图/录屏、相关链接、关联 Issue 等。
      placeholder: |
        - 相关 Issue: #...
        - 截图/录屏: ...
    validations:
      required: false

